-- -----------------------------------------------------
-- Add queries below for the website. 
-- Please comment above every query so we can tell what they do.
-- When done with a query check it off on Github issues so everyone knows that it is finished.
-- MAKE SURE THE PUSH YOUR CHANGES
-- -----------------------------------------------------